# Generated by Django 4.2.7 on 2023-11-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('N', 'General'), ('C', 'Pecho'), ('B', 'Espalda'), ('A', 'Brazos'), ('S', 'Hombros'), ('L', 'Piernas')], default='N', max_length=1)),
                ('videoURL', models.CharField(max_length=100)),
                ('isPrivate', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=200)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.client')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer')),
                ('trainingSessions', models.ManyToManyField(to='fitness_app.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.client')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
