# Generated by Django 4.2.7 on 2023-11-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='objective',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.client')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.trainer')),
            ],
        ),
    ]
