# Generated by Django 4.2.7 on 2023-11-29 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_client_objective_rating_comment_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='imc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='measureDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='rep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='sets',
            field=models.IntegerField(default=0),
        ),
    ]
