# Generated by Django 4.2.7 on 2023-12-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_client_imc_client_measuredate_client_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.client'),
        ),
    ]
