# Generated by Django 4.2.7 on 2023-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_trainingsession_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
